In [1]:
import math
import random
import numpy as np
import matplotlib.pyplot as plt

In [161]:
def getMaxRuleSpaceSize(domainY,domainX,y,x):
    return (len(domainY) ** len(y))*(len(domainX) ** len(x))

def getRuleSpace(noVar, domain):
    space = []
    count = noVar
    maxSize = len(domainX) ** noVar
    #print(maxSize)
    while count > 0:
        no = (len(domainX) ** count)
        repeatCount = int(no / len(domainX))
        repeatCount2 = int(maxSize/no)
        temp = []
        for j in range(repeatCount2):
            for x in domainX:
                for i in range(repeatCount):
                    temp.append(x)
        space.append(temp)
        count -= 1
    return space
           
def inv(space):
    inverse = []
    for col in range(len(space[0])):
        temp = []
        for row in range(len(space)):
            temp.append(space[row][col])
        inverse.append(temp)
    return inverse

#neighborsFromRadious returns an array with the relative reference of the neighborhood
#radious = size
#neighborhoodType = type of the neighborhood, 0 = moore, 1 = von neumann
def neighborsFromRadious(radious,neighborhoodType = 0):
    neighbors = []
    if neighborhoodType == 0:
        for i in range(-radious,radious+1):
            for j in range(-radious,radious+1):
                neighbors.append([i,j])
    elif neighborhoodType == 1:
        for i in range(-radious,radious+1):
            for j in range(-radious,radious+1):
                if abs(i) + abs(j) <= radious:
                    neighbors.append([i,j])
    else:
        neighbors = None
        print("type not defined")
    
    return neighbors

In [124]:
domainY = [0,1]
domainX = [0,1]
y = [0]
x = [0,1]

In [96]:
getMaxRuleSpaceSize(domainY,domainX,y,x)

16

In [137]:
spaceY = np.array(getRuleSpace(len(domainX) ** len(x),domainY))
spaceX = np.array(getRuleSpace(len(x),domainX))

In [134]:
for i in range(len(spaceY[0])):
    print(np.array(spaceY)[:,i])

[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[0 1 1 0]
[0 1 1 1]
[1 0 0 0]
[1 0 0 1]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]


In [139]:
for i in range(len(spaceX[0])):
    print(np.array(spaceX)[:,i])

[0 0]
[0 1]
[1 0]
[1 1]


In [166]:
neighborsFromRadious(2,1)

[[-2, 0],
 [-1, -1],
 [-1, 0],
 [-1, 1],
 [0, -2],
 [0, -1],
 [0, 0],
 [0, 1],
 [0, 2],
 [1, -1],
 [1, 0],
 [1, 1],
 [2, 0]]

In [ ]:
paddingType = 1
paddingValue = 0
dim = 0
for r in range(1,10):
    for step in range(1,timesteps):
        df1 = pd.read_csv("data/step_{}.csv".format(step-1),header=None).values
        df2 = pd.read_csv("data/step_{}.csv".format(step),header=None).values
        dim = df1.shape
        planned = df1.reshape(-1) 
        processed = []
        for i in range(dim[0]):
            for j in range(dim[1]):
                neighbors = getNeighbors([i,j],kernel,dim)
                values = getNeighborsValue(planned,neighbors,paddingType,paddingValue)
                if values != None:
                    temp = []
                    for key in values:
                        temp.append(values[key])
                    temp.append(df2[i][j])
                    processed.append(temp)
            